# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller Specification for Campus Digital Voting Platform
Bundles Native PyWebView Desktop Launcher, HTTP Proxy Client, and compiled React Multi-Portal Frontend
into a single self-contained standalone windowed executable (Zero Local Database).
"""
import glob
import os
import sys
from PyInstaller.utils.hooks import copy_metadata, collect_data_files, collect_all

_repo_root = os.path.dirname(os.path.abspath(SPEC))
source_script = os.path.join(_repo_root, "app_launcher.py")

# --------------------------------------------------------------------------
# Detect obfuscated entry script if generated by PyArmor
# --------------------------------------------------------------------------
_obf_dirs = [
    os.path.join(_repo_root, "build_obf"),
    os.path.join(_repo_root, "obf"),
    os.path.join(_repo_root, "dist_obf"),
]

obf_script = None
pathex = [_repo_root, os.path.join(_repo_root, "backend")]

for obf_dir in _obf_dirs:
    candidate = os.path.join(obf_dir, "app_launcher.py")
    if os.path.isfile(candidate):
        obf_script = candidate
        if obf_dir not in pathex:
            pathex.insert(0, obf_dir)
        break

# --------------------------------------------------------------------------
# Bundle the built frontend multi-portal assets (dist/)
# --------------------------------------------------------------------------
datas = []
binaries = []

_fe_candidates = [
    os.path.join(_repo_root, "dist_frontend"),
    os.path.join(_repo_root, "frontend", "dist"),
]
_fe_src = next((p for p in _fe_candidates if os.path.isdir(p)), None)
if _fe_src is None:
    raise SystemExit(
        "Frontend build not found. Run `npm --prefix frontend run build` before packaging."
    )

datas.append((_fe_src, "dist_frontend"))
datas.append((_fe_src, "frontend_dist"))

# --------------------------------------------------------------------------
# Detect and bundle PyArmor runtime packages if present
# --------------------------------------------------------------------------
pyarmor_search_roots = [_repo_root] + _obf_dirs
pyarmor_runtime_pkgs = set()

for s_root in pyarmor_search_roots:
    if os.path.isdir(s_root):
        for r_path in glob.glob(os.path.join(s_root, "pyarmor_runtime_*")):
            if os.path.isdir(r_path):
                pkg_name = os.path.basename(r_path)
                pyarmor_runtime_pkgs.add(pkg_name)
                datas.append((r_path, pkg_name))
                if s_root not in pathex:
                    pathex.append(s_root)

# --------------------------------------------------------------------------
# Collect metadata & dependencies for core web and networking packages
# --------------------------------------------------------------------------
for pkg in ("fastapi", "starlette", "uvicorn", "httpx", "httpcore", "anyio", "pydantic", "pydantic_core", "pydantic_settings"):
    try:
        datas += copy_metadata(pkg)
    except Exception:
        pass

hiddenimports_extra = []
for pkg in ("httpx", "httpcore", "fastapi", "starlette", "pydantic", "pydantic_core"):
    try:
        c_datas, c_binaries, c_hiddenimports = collect_all(pkg)
        datas += c_datas
        binaries += c_binaries
        hiddenimports_extra += c_hiddenimports
    except Exception:
        pass

datas += collect_data_files("certifi")
datas += collect_data_files("webview")

hiddenimports = [
    "httpx",
    "httpcore",
    "fastapi",
    "fastapi.responses",
    "fastapi.staticfiles",
    "starlette",
    "starlette.responses",
    "starlette.staticfiles",
    "starlette.routing",
    "starlette.middleware",
    "starlette.datastructures",
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "h11",
    "anyio",
    "anyio._backends",
    "anyio._backends._asyncio",
    "sniffio",
    "pydantic",
    "pydantic.v1",
    "pydantic_core",
    "pydantic_core._pydantic_core",
    "pydantic_core.core_schema",
    "pydantic_settings",
    "annotated_types",
    "webview",
    "webview.platforms.edgechromium",
    "webview.platforms.winforms",
    "clr_loader",
    "pythonnet",
] + list(pyarmor_runtime_pkgs) + hiddenimports_extra

excludes = [
    "torch",
    "transformers",
    "sklearn",
    "scipy",
    "tensorflow",
    "onnxruntime",
    "dask",
    "cupy",
    "matplotlib",
    "jupyter",
    "notebook",
    "IPython",
    "playwright",
    "pytest",
    "pandas",
    "numpy",
    "PIL",
    "lxml",
    "sqlalchemy",
    "alembic",
    "langchain",
    "langchain_core",
    "langchain_openai",
    "langgraph",
    "openai",
    "tiktoken",
]

a = Analysis(
    [source_script],
    pathex=pathex,
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

if obf_script:
    new_scripts = []
    for item in a.scripts:
        if item[0] == "app_launcher" or item[1] == source_script:
            new_scripts.append((item[0], obf_script, item[2]))
        else:
            new_scripts.append(item)
    a.scripts = new_scripts
    a.pure = [item for item in a.pure if item[0] != "app_launcher"]

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="Campus-Voting-Platform",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
