"""
Database facade module:
Re-exports core database connection methods and all repository functions
for backwards compatibility and clean unified access.
"""
from core import get_db, init_db
from repositories import (
    get_admin_by_email,
    get_all_admins,
    add_admin,
    update_admin,
    delete_admin,
    create_admin_request,
    get_all_admin_requests,
    approve_admin_request,
    reject_admin_request,
    delete_admin_request,
    get_campuses,
    get_campus_by_id,
    add_campus,
    update_campus,
    delete_campus,
    normalize_campus_name,
    STANDARD_CLUBS,
    ensure_campus_clubs,
    get_clubs,
    get_club_by_id,
    add_club,
    update_club,
    toggle_club_status,
    delete_club,
    get_students,
    get_student_by_id,
    get_student_by_email,
    get_student_by_email_or_id,
    add_student,
    bulk_add_students,
    delete_student,
    clear_all_students,
    get_candidates_by_club,
    get_candidate_by_id,
    add_candidate,
    delete_candidate,
    has_student_voted_in_club,
    cast_vote,
    cast_multi_votes,
    get_all_votes_with_details,
    get_total_votes_count,
)

# Auto-initialize DB tables on module load
init_db()

__all__ = [
    "get_db",
    "init_db",
    "get_admin_by_email",
    "get_all_admins",
    "add_admin",
    "update_admin",
    "delete_admin",
    "create_admin_request",
    "get_all_admin_requests",
    "approve_admin_request",
    "reject_admin_request",
    "delete_admin_request",
    "get_campuses",
    "get_campus_by_id",
    "add_campus",
    "update_campus",
    "delete_campus",
    "normalize_campus_name",
    "STANDARD_CLUBS",
    "ensure_campus_clubs",
    "get_clubs",
    "get_club_by_id",
    "add_club",
    "update_club",
    "toggle_club_status",
    "delete_club",
    "get_students",
    "get_student_by_id",
    "get_student_by_email",
    "get_student_by_email_or_id",
    "add_student",
    "bulk_add_students",
    "delete_student",
    "clear_all_students",
    "get_candidates_by_club",
    "get_candidate_by_id",
    "add_candidate",
    "delete_candidate",
    "has_student_voted_in_club",
    "cast_vote",
    "cast_multi_votes",
    "get_all_votes_with_details",
    "get_total_votes_count",
]
